auth:
  root:
    user: root-user
    password: root-password
  service:
    user: user
    password: password

management:
  endpoints.web:
    exposure.include: health,info,env,beans,conditions
    base-path: /app
  endpoint:
    health.show-details: always