auth:
  root:
    user: ${admin.login:root-user}
    password: ${admin.password:root-password}
  service:
    user: ${user.login:default-user}
    password: ${user.password:default-password}

management:
  endpoints.web:
    exposure.include: health,info,env,beans,conditions
    base-path: /app
  endpoint:
    health.show-details: always